### ISSUE TITLE
plugins branch still requires ruby 1.9?

### ISSUE THREAD

**Issue by itsakap** [colibri-software/locomotive_engine#4]
Hi!

First time opening an issue ever! Yay.

I am using Locomotive for a simple project and want to make use of some plugins. It seems I have trouble installing Engine with the plugins feature because of my Ruby version. I noticed this requirement was removed in locomotive_plugins but Engine seems to still try and install with the 1.9 requirement. Please advise, and thanks in advance.

**Comment by Antiblanks** [comment]
Maybe a bit late to this party but I was actually struggling with similar dependency issues trying to run the plugins branch using Ruby 2.x.x. I fixed the issue by forking the repos, checking out the plugins branch and changing the locomotive_plugins dependency to be 1.2.0 (latest at time of writing). I can now work with plugins! The change only took 5 mins but please feel free to use my forked version if you like: Plugins branch of https://github.com/Antiblanks/locomotive_engine.git
